# Generated by Django 3.0.8 on 2020-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0004_auto_20200808_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_username', models.CharField(max_length=10)),
                ('buyer_username', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
                ('product_title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
