# Generated by Django 3.0.8 on 2020-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('stationery', 'Stationery'), ('sports', 'Sports'), ('others', 'Others')], max_length=15)),
                ('product_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
