# Generated by Django 3.0.8 on 2020-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellform',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
