# Generated by Django 3.0.8 on 2020-07-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200718_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellform',
            old_name='img1',
            new_name='img',
        ),
    ]
