# Generated by Django 3.0.8 on 2020-07-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200718_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='others',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sports',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
