# Generated by Django 3.0.8 on 2020-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_books_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('product_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='media/pics')),
            ],
        ),
    ]
