# Generated by Django 3.0.8 on 2020-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='category',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourites',
            name='favourite_username',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
