# Generated by Django 3.0.8 on 2020-07-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
