# Generated by Django 3.0.8 on 2020-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buysell', '0002_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_username', models.CharField(max_length=10)),
                ('buyer_username', models.CharField(max_length=10)),
                ('product_title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
