# Generated by Django 3.0.8 on 2020-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
