# Generated by Django 3.0.8 on 2020-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200717_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('product_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
