# Generated by Django 3.0.8 on 2020-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200717_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellform',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
