# Generated by Django 3.0.8 on 2020-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200718_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellform',
            name='img',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
