# Generated by Django 3.0.8 on 2020-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200718_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellform',
            name='img',
        ),
        migrations.AddField(
            model_name='sellform',
            name='img1',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
