# Generated by Django 3.0.8 on 2020-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20200719_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='end_date',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventform',
            name='start_date',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
