# Generated by Django 3.0.8 on 2020-07-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
