# Generated by Django 3.0.8 on 2020-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_signup_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
